Modest update to thor version dependency.
Meant to get around this:

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: motherbrain requires thor (~> 0.18.0); berkshelf requires thor (~> 0.19)